export const MIN_DURATION_FOR_ADVANCED_THUMBNAIL_SECONDS = 10;
export const DEFAULT_THUMBNAIL_EXTRACT_SECONDS = 3;
export const FALLBACK_THUMBNAIL_EXTRACT_SECONDS = 0;

export const THUMBNAIL_WIDTH = 512;
export const THUMBNAIL_HEIGHT = 288;
